import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {plan,apply,verify,rollback} from '../tools/lib/installations.mjs';
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'skill-install-'));const sourceRoot=path.join(root,'source'),homeDir=path.join(root,'home');const skill=path.join(sourceRoot,'.agents/skills/alpha');fs.mkdirSync(skill,{recursive:true});fs.writeFileSync(path.join(skill,'SKILL.md'),'alpha');fs.writeFileSync(path.join(skill,'run.sh'),'#!/bin/sh\n',{mode:0o755});const catalog={profiles:{codex:['alpha'],cursor:['alpha'],'claude-code':['alpha']},skills:[{name:'alpha',sourceType:'Owned'},{name:'retired',sourceType:'Owned'},{name:'external',sourceType:'External'}]};return {root,sourceRoot,homeDir,catalog,profile:'codex',statePath:path.join(root,'state.json'),backupRoot:path.join(root,'backups')};}
function clean(f){fs.rmSync(f.root,{recursive:true,force:true})}
test('install, verify and repeat preserve scripts and unrelated skills',()=>{const f=fixture();try{const unrelated=path.join(f.homeDir,'.agents/skills/unrelated');fs.mkdirSync(unrelated,{recursive:true});fs.writeFileSync(path.join(unrelated,'SKILL.md'),'leave');const p=plan(f);apply(p,{...f,sourceRevision:'test'});assert.deepEqual(verify(p),[]);assert.ok(fs.statSync(path.join(f.homeDir,'.agents/skills/alpha/run.sh')).mode&0o111);assert.equal(plan({...f,state:JSON.parse(fs.readFileSync(f.statePath))}).ops.length,0);assert.equal(fs.readFileSync(path.join(unrelated,'SKILL.md'),'utf8'),'leave');}finally{clean(f)}});
test('adoption backs up unique local content and rollback restores it',()=>{const f=fixture();try{const dest=path.join(f.homeDir,'.agents/skills/alpha');fs.mkdirSync(dest,{recursive:true});fs.writeFileSync(path.join(dest,'SKILL.md'),'unique');assert.throws(()=>plan(f),/Unmanaged/);const p=plan({...f,adoptExisting:true});const result=apply(p,{...f,sourceRevision:'test'});rollback(result.backup,f.statePath);assert.equal(fs.readFileSync(path.join(dest,'SKILL.md'),'utf8'),'unique');assert.ok(!fs.lstatSync(dest).isSymbolicLink());}finally{clean(f)}});
test('all destinations are checked before apply; missing dependencies block planning',()=>{const f=fixture();try{const p=plan(f);fs.mkdirSync(path.join(f.homeDir,'.agents/skills/alpha'),{recursive:true});fs.writeFileSync(path.join(f.homeDir,'.agents/skills/alpha/SKILL.md'),'new');assert.throws(()=>apply(p,{...f,sourceRevision:'test'}),/changed after preview/);f.catalog.skills[0].dependencies=['absent'];assert.throws(()=>plan(f),/Missing dependency/);}finally{clean(f)}});
test('retirement is limited to catalog identities and is reversible',()=>{const f=fixture();try{for(const n of ['retired','external','unrelated']){const p=path.join(f.homeDir,'.agents/skills',n);fs.mkdirSync(p,{recursive:true});fs.writeFileSync(path.join(p,'SKILL.md'),n)}const p=plan({...f,adoptExisting:true});const r=apply(p,{...f,sourceRevision:'test'});assert.deepEqual(verify(p),[]);assert.ok(fs.existsSync(path.join(f.homeDir,'.agents/skills/unrelated')));rollback(r.backup,f.statePath);assert.ok(fs.existsSync(path.join(f.homeDir,'.agents/skills/retired/SKILL.md')));}finally{clean(f)}});
test('rollback refuses newer changes and unsafe profile identities',()=>{const f=fixture();try{const p=plan(f),r=apply(p,{...f,sourceRevision:'test'});fs.unlinkSync(p.expected[0].destination);fs.mkdirSync(p.expected[0].destination);fs.writeFileSync(path.join(p.expected[0].destination,'SKILL.md'),'newer');assert.throws(()=>rollback(r.backup,f.statePath),/newer work/);f.catalog.profiles.codex=['../outside'];assert.throws(()=>plan(f),/Unknown profile/);}finally{clean(f)}});
test('missing sources block all writes and source changes update verification',()=>{const f=fixture();try{const p=plan(f);const r=apply(p,{...f,sourceRevision:'one'});fs.writeFileSync(path.join(f.sourceRoot,'.agents/skills/alpha/SKILL.md'),'updated source');const next=plan({...f,state:JSON.parse(fs.readFileSync(f.statePath))});assert.equal(next.ops.length,0);assert.deepEqual(verify(next),[]);fs.rmSync(path.join(f.sourceRoot,'.agents/skills/alpha'),{recursive:true});assert.throws(()=>plan(f),/Missing source/);}finally{clean(f)}});
